## Part 1: Theoretical Questions

### 1. What are the different data structures used in Tensorflow?. Give some examples.

TensorFlow provides several data structures that are commonly used in deep learning applications. Some of the key data structures in TensorFlow include:

1. **Tensors**: Tensors are the fundamental data structures in TensorFlow. They are multi-dimensional arrays that can represent scalars, vectors, matrices, or higher-dimensional arrays. Tensors are used to store and manipulate data in TensorFlow computations. Examples include:

   - Scalar: `tf.constant(5)` represents a scalar tensor with a value of 5.
   - Vector: `tf.constant([1, 2, 3])` represents a 1D tensor with values [1, 2, 3].
   - Matrix: `tf.constant([[1, 2], [3, 4]])` represents a 2D tensor with values [[1, 2], [3, 4]].

2. **Variables**: Variables are tensors that hold values that can be updated during training. They are commonly used to represent model parameters that are optimized through gradient descent or other optimization algorithms. Examples include:

   - Weight matrix: `tf.Variable(tf.random.normal(shape=(784, 256)))` represents a variable tensor initialized with random values for a neural network weight matrix.
   - Bias vector: `tf.Variable(tf.zeros(shape=(256,)))` represents a variable tensor initialized with zeros for a neural network bias vector.

3. **Constants**: Constants are tensors with fixed values that remain unchanged during execution. They are typically used to represent hyperparameters, fixed values, or other constant values in a TensorFlow program. Examples include:

   - Learning rate: `tf.constant(0.001)` represents a constant tensor with a fixed learning rate value.
   - Number of epochs: `tf.constant(10)` represents a constant tensor with the number of training epochs.

4. **Sparse tensors**: Sparse tensors are specialized tensors used to efficiently represent and manipulate tensors with a large number of zero values. They store only the non-zero values along with their indices. Examples include:

   - `tf.SparseTensor` represents a sparse tensor with values and indices.

These are some of the key data structures used in TensorFlow, and they play essential roles in representing and manipulating data in deep learning models.

### 2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.

In [3]:
pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 524.1/524.1 MB 2.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 78.2 MB/s eta 0:00:00ta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 64.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.5/126.5 kB 23.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 64.2 MB/s eta 0:00:0000:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 12.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.9/22.9 MB 55.1 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 11.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 15.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.8/440.8 kB 50.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 83.7 MB/s eta 0:00:00ta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.5/242.5 kB 33.8 MB/s eta

In TensorFlow, constants and variables differ in their mutability and behavior during execution. Here's a detailed explanation of the differences between TensorFlow constants and variables:

1. **Mutability**: Constants are immutable, meaning their values cannot be changed once they are defined. On the other hand, variables are mutable, allowing their values to be updated during program execution.

2. **Usage and Behavior**:

   - Constants: Constants are typically used to store fixed values, hyperparameters, or other values that do not need to be updated during training or inference. They are created using the `tf.constant()` function and retain the same value throughout the program's execution.

In [5]:
import tensorflow as tf
# Creating a constant
constant = tf.constant(5)

# Printing the constant's value
print(constant)  

tf.Tensor(5, shape=(), dtype=int32)


- Variables: Variables, on the other hand, are used to represent model parameters that need to be optimized during training. They are created using the `tf.Variable()` function and can be updated using methods like `assign()` or through training operations. Variables are used to store and update values such as weights and biases in neural networks.

In [6]:
# Creating a variable
variable = tf.Variable(2)

# Printing the initial value
print(variable)  

# Updating the variable's value
variable.assign(3)

# Printing the updated value
print(variable)  

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>


So, the key differences between TensorFlow constants and variables are their mutability and intended usage. Constants hold fixed values that cannot be changed once defined, while variables are mutable and allow for updates during program execution, making them suitable for representing and optimizing model parameters.

### 3. Describe the process of matrix addition, multiplication, and element wise operations in TensorFlow.

In TensorFlow, matrix addition, multiplication, and element-wise operations can be performed using various functions and operators. Here's an overview of each operation and the corresponding TensorFlow functions or operators used:

1. **Matrix Addition**:

   Matrix addition is performed by adding corresponding elements of two matrices with the same dimensions. In TensorFlow, you can perform matrix addition using the `tf.add()` function or the `+` operator.


   In this example, we define two matrices (`matrix1` and `matrix2`) and use `tf.add()` to perform matrix addition, resulting in a new matrix (`result`) that contains the element-wise sum of the input matrices.

2. **Matrix Multiplication**:

   Matrix multiplication is performed by multiplying corresponding elements of rows in the first matrix with columns in the second matrix and summing the results. In TensorFlow, you can perform matrix multiplication using the `tf.matmul()` function or the `@` operator.



In [7]:
# Define two matrices
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Perform matrix addition
result = tf.add(matrix1, matrix2)

# Print the result
print(result)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


3. **Element-wise Operations**:

   Element-wise operations are performed by applying an operation to each corresponding element of two matrices or a matrix and a scalar. In TensorFlow, element-wise operations can be performed using functions like `tf.add()`, `tf.subtract()`, `tf.multiply()`, `tf.divide()`, and so on.

In [8]:
# Define a matrix and a scalar
matrix = tf.constant([[1, 2], [3, 4]])
scalar = tf.constant(2)

# Perform element-wise operations
result_add = tf.add(matrix, scalar)
result_sub = tf.subtract(matrix, scalar)
result_mul = tf.multiply(matrix, scalar)
result_div = tf.divide(matrix, scalar)

# Print the results
print(result_add)
print(result_sub)
print(result_mul)
print(result_div)

tf.Tensor(
[[3 4]
 [5 6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-1  0]
 [ 1  2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.5 1. ]
 [1.5 2. ]], shape=(2, 2), dtype=float64)


These operations form the foundation for many mathematical computations in TensorFlow and are essential for various deep learning tasks involving matrix manipulation and transformation.

## Part 2: Practical Implementation

### Task 1: Creating and Manipulating Matrices

### 1. Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the values of matrix A

In [11]:
A = tf.random.normal(shape=(2, 2))
print(A)

tf.Tensor(
[[-0.56773347 -1.1200626 ]
 [ 0.4115314   1.3779663 ]], shape=(2, 2), dtype=float32)


### 2. Create a Gaussian matrix B with dimensions x, using TensorFlow's truncated_normal function. Display the values of matrix B

In [12]:
x = 3
B = tf.random.truncated_normal(shape=(x, x))
print(B)

tf.Tensor(
[[ 0.2069356  -0.8287504  -0.7488676 ]
 [ 0.23174791  0.01931232 -0.20348339]
 [ 0.5933986   0.6130777  -0.37511602]], shape=(3, 3), dtype=float32)


### 3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 2 and a standard deviation of 0.x, using TensorFlow's random.normal function. Display the values of matrix C

In [13]:
mean = 2.0
stddev = 0.1
C = tf.random.normal(shape=(2, 2), mean=mean, stddev=stddev)
print(C)

tf.Tensor(
[[1.7963961 1.9330441]
 [1.8939402 2.1718035]], shape=(2, 2), dtype=float32)


### 4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D

In [14]:
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

D = tf.add(A, B)

print(D)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


### 5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [17]:
C = tf.constant([[1,2],[3,4]])
D = tf.constant([[5,6],[7,8]])

E=tf.matmul(C,D)

print(E)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


### Task 3: Performing Additional Matrix Operations

### 1. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform functions

In [27]:
F = tf.random.uniform(shape = (2,2))
print(F)

tf.Tensor(
[[0.7033316  0.18596232]
 [0.0347805  0.16601074]], shape=(2, 2), dtype=float32)


### 2. Calculate the transpose of matrix F and store the result in matrix G

In [28]:
G= tf.transpose(F)
print(G)

tf.Tensor(
[[0.7033316  0.0347805 ]
 [0.18596232 0.16601074]], shape=(2, 2), dtype=float32)


### 3. Calculate the element wise exponential of matrix F and store the result in matrix H

In [29]:
H = tf.exp(F)
print(H)

tf.Tensor(
[[2.020473  1.2043769]
 [1.0353924 1.1805857]], shape=(2, 2), dtype=float32)


### 4. Create a matrix I by concatenating matrix F and matrix G horizontally

In [30]:
I = tf.concat([F,G],axis=1)
print(I)

tf.Tensor(
[[0.7033316  0.18596232 0.7033316  0.0347805 ]
 [0.0347805  0.16601074 0.18596232 0.16601074]], shape=(2, 4), dtype=float32)


### 5. Create a matrix J by concatenating matrix F and matrix H vertically.

In [31]:
J = tf.concat([F,G],axis=0)
print(J)

tf.Tensor(
[[0.7033316  0.18596232]
 [0.0347805  0.16601074]
 [0.7033316  0.0347805 ]
 [0.18596232 0.16601074]], shape=(4, 2), dtype=float32)
