In [1]:
#Consider the below code to answer further questions:
import numpy as np
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_)

### 1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes, there is a difference in the data type of variables list_ and array_list.

list_ is a Python list and array_list is a numpy array.

We can print the data types of both variables using the type() function as shown below:

In [2]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


### 2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [3]:
for element in list_:
    print(type(element))

for element in np.nditer(array_list):
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### 3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
array_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [9]:
'''Yes, there will be a difference in the data type of elements present in both the variables, 
list_ and array_list. After specifying the dtype as int, the elements of array_list will be of integer 
data type.'''

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data type of elements in list_:")
for i in list_:
    print(type(i))

print("\nData type of elements in array_list:")
for i in np.nditer(array_list):
    print(type(i))
    
print(array_list.dtype) 

Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list:
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
int64


In [10]:
#Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

### 4. Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

In [13]:
print(num_array.shape)
print(num_array.size)

(2, 3)
6


### 5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [14]:
zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 6. Create an identity matrix of shape (5,5) using numpy functions?

In [17]:
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
