In [ ]:
import numpy as np 

In [ ]:
l = [1,2,3,4,5]

In [ ]:
arr = np.array(l)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [ ]:
arr1 = np.array([[1,2,3] , [2,3,4]])

In [ ]:
arr.ndim

1

In [ ]:
arr1.ndim

2

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
mat = np.matrix(l)

In [ ]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [ ]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
a = arr

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr[0] = 100

In [ ]:
arr

array([100,   2,   3,   4,   5])

In [ ]:
a

array([100,   2,   3,   4,   5])

In [ ]:
b = np.copy(arr)

In [ ]:
b

array([100,   2,   3,   4,   5])

In [ ]:
b[0] = 234

In [ ]:
b

array([234,   2,   3,   4,   5])

In [ ]:
arr

array([100,   2,   3,   4,   5])

In [ ]:
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [ ]:
iterable  = (i*i for i in range(5))

In [ ]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
np.fromstring('23 45 56',sep  = ' ' )

array([23., 45., 56.])

In [ ]:
np.fromstring('23,45,56',sep  = ',' )

array([23., 45., 56.])

In [ ]:
arr

array([100,   2,   3,   4,   5])

In [ ]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
arr.ndim

1

In [ ]:
arr1.ndim

2

In [ ]:
arr.size

5

In [ ]:
arr1.size

6

In [ ]:
arr.shape

(5,)

In [ ]:
arr1.shape

(2, 3)

In [ ]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr1.dtype

dtype('int64')